### ISSUE TITLE
Error when trying to activate another method in backend..

### ISSUE THREAD

**Issue by rbuelund** [akeeba/loginguard#115] opened 2021-11-03 09:25 UTC
Please read the README.md in the repository's root and the support resources before submitting an issue.

### Steps to reproduce the issue

Deactivate the LoginGuard system plugin
Login to backend
Select own user
"Add a new code by e-mail" - activate new method

### Expected result

An e-mail with activation should be sent

### Actual result
Error:
Class 'LoginGuardHelperTfa' not found
File /components/com_loginguard/controllers/method.php Line 476 

#0 /var/www/www.xxxxxx.dk/www/components/com_loginguard/controllers/method.php(80): LoginGuardControllerMethod->_assertCanEdit(Object(Joomla\CMS\User\User))
#1 /var/www/www.xxxxxx.dk/www/libraries/src/MVC/Controller/BaseController.php(702): LoginGuardControllerMethod->add()
#2 /var/www/www.xxxxxx.dk/www/components/com_loginguard/controllers/method.php(61): Joomla\CMS\MVC\Controller\BaseController->execute('add')
#3 /var/www/www.xxxxxx.dk/www/administrator/components/com_loginguard/loginguard.php(80): LoginGuardControllerMethod->execute('add')
#4 /var/www/www.xxxxxx.dk/www/libraries/src/Component/ComponentHelper.php(402): require_once('/var/www/www.ho...')
#5 /var/www/www.xxxxxx.dk/www/libraries/src/Component/ComponentHelper.php(377): Joomla\CMS\Component\ComponentHelper::executeComponent('/var/www/www.ho...')
#6 /var/www/www.xxxxxx.dk/www/libraries/src/Application/AdministratorApplication.php(101): Joomla\CMS\Component\ComponentHelper::renderComponent('com_loginguard')
#7 /var/www/www.xxxxxx.dk/www/libraries/src/Application/AdministratorApplication.php(159): Joomla\CMS\Application\AdministratorApplication->dispatch()
#8 /var/www/www.xxxxxx.dk/www/libraries/src/Application/CMSApplication.php(225): Joomla\CMS\Application\AdministratorApplication->doExecute()
#9 /var/www/www.xxxxxx.dk/www/administrator/index.php(51): Joomla\CMS\Application\CMSApplication->execute()
#10 {main}

### Troubleshooting already performed

Do not know aht to do ??

#### Mandatory information

Issues without this information can not and _will not_ be replied to.
 Loginguard: 5.0.4
* **Joomla! version 3.10.3
* **PHP version 7.4.24
* **Am I using HTTPS Yes
* **Server Operating System  Linux 
* **My device's Operating System: Windows 
* **My device's Operating System version: windows 10
* **Browser**: Chrome, Firefox
* **Browser version: latest

**Comment by nikosdion** [comment] 2021-11-03 09:50
Duplicate of https://github.com/akeeba/loginguard/issues/114 which has already been resolved.

A new version will be released shortly. As a result I am closing this.

**Closed by nikosdion** 2021-11-03 09:50 UTC
Labels: bug

**Comment by nikosdion** [comment] 2021-11-03 20:16
I cannot reproduce your issue using the currently latest published version (5.0.4) on Joomla 4.0.4 running on PHP 8.0.12.

This is a brand new site set up for the purpose of testing. I installed Akeeba LoginGuard 5.0.4 and only enabled the following plugins:

* LoginGuard - Authentication Code by Email
* System - Akeeba LoginGuard protection
* User - Akeeba LoginGuard protection

I am able to set up Two Step Verification from the backend or the frontend. Logging into the frontend I am sent the email with the code which I can enter just fine.

Enabling the LoginGuard - Time-based One Time Password (Google Authenticator) and publishing it EITHER before OR after the email plugin makes absolutely no difference whatsoever.

Furthermore, the code referenced in your error message is only called when you are ADDING a Two Step Verification method, not when you are logging in.

The only reasonable explanation for what you describe is that the LoginGuard system plugin is not loaded. This is the plugin which is responsible for loading the helper class referenced in your error message. The plugin the documentation tells you that needs to be enabled at all times. Some reasons for that is that you changed its access from Public to something different, you unpublished it, you deleted/renamed its files or folder. In any case, this issue appears to be thoroughly self–inflicted. I am therefore locking this issue, marking it only as invalid. Do NOT make a new issue about this, do NOT make a new comment about this.

I am noting that out of the three issues you have filed in this repository one was something a third party component did, one was a duplicate of another issue (which means you didn't look before asking) and one is self–inflicted. I am also noting that this morning you kept pestering me about what is ultimately a self–inflicted issue. This will be taken into account for any issues you submit henceforth.
