### ISSUE TITLE
Call to a member function methodExists() on boolean

### ISSUE THREAD

**Issue by PhilETaylor** [akeeba/loginguard#22] opened 2017-03-12 17:59 UTC
<img width="692" alt="screen shot 2017-03-12 at 17 58 09" src="https://cloud.githubusercontent.com/assets/400092/23834380/848ea85c-074d-11e7-8a86-7a813068200f.png">

Click on any of those blue buttons and get the error message:

<img width="565" alt="screen shot 2017-03-12 at 17 59 14" src="https://cloud.githubusercontent.com/assets/400092/23834385/9e0e3072-074d-11e7-8bf4-695f52cd6670.png">

[systeminfo-2017-03-12T17-59-27+00-00.txt](https://github.com/akeeba/loginguard/files/836767/systeminfo-2017-03-12T17-59-27.00-00.txt)

**Comment by nikosdion** [comment] 2017-03-12 19:25
Cannot reproduce on Ubuntu Linux 16.10 (case sensitive Ext4 filesystem - that's my main dev machine BTW), CentOS (live Rochen server) or Windows 10 (case sensitive NTFS filesystem; BTW that's the secondary dev machine and the one I'm using for presentations). Note: I am using Joomla! 3.6.5. 

For what it's worth, it's the same problem as gh-23 as far as I can tell. The only place where I haev a methodExists method is in LoginGuardModelMethod which is loaded using the same way from the front-end.

Shame on me for trying to use Joomla! the way it says it's supposed to be used instead of using my own library for everything :p Anyway, since this is a J! bug I am closing this one too as wontfix.

**Closed by nikosdion** 2017-03-12 19:25 UTC

**Comment by PhilETaylor** [comment] 2017-03-12 19:27
yup - only occurs in Joomla-cms@staging and not 3.6.4 :(

**Comment by nikosdion** [comment] 2017-03-12 19:27
I think I might shut down the computer and go drink now...

**Comment by PhilETaylor** [comment] 2017-03-12 19:28
Im about to leave the office and walk home... Its sunday night after all...
