### ISSUE TITLE
Login Guard/Users: Unhandled Exception

### ISSUE THREAD

**Issue by peterpeter** [akeeba/loginguard#88] opened 2020-08-28 08:49 UTC
Hi
I've installed Login Guard, and when I click on the 'Users' button in the upper left corner from Login Guard's Dashboard, I'll get a unhandled Exception (see attached screenshot)

![grafik](https://user-images.githubusercontent.com/485313/91540901-c7945f80-e91b-11ea-9c72-30d7236438b5.png)

![grafik](https://user-images.githubusercontent.com/485313/91540988-ec88d280-e91b-11ea-865f-4f436ecfd4fa.png)

Let me know, if you need more informations

**Comment by nikosdion** [comment] 2020-08-28 09:27
Installing LoginGuard did not install the latest version of FOF. Try installing it from [our downloads page](https://www.akeeba.com/download.html). At the time of this writing the latest version is 3.6.2.

**Comment by nikosdion** [comment] 2020-08-28 09:28
Note that you _may_ have to also clean Joomla's cache – even if you have not enabled caching on your site.

**Comment by peterpeter** [comment] 2020-08-28 13:48
I guess I have the latest versions and cache was cleaned too - but the error is still there. But whatever this view should show - the Login Guard works in the frontend flawless so far - so there is no problem a.t.m., at least for me 😉
![grafik](https://user-images.githubusercontent.com/485313/91568887-ec053180-e945-11ea-8223-70ed8a9a88f3.png)

**Comment by nikosdion** [comment] 2020-08-28 13:56
The message complains that the file `libraries/fof30/ViewTemplates/Common/browse.blade.php` does not exist on your site, but this is part of FOF 3.6.2 (actually: part of FOF since 3.5.4). Unless you or someone else (e.g. your host) has remove that file there is no reason for that message to appear. I checked my test site, I don't get that error, I see the list of users.

**Comment by peterpeter** [comment] 2020-08-28 14:20
I reinstalled everthing - the latest FOF separately. Filezilla 'says' this file you mentioned is there. But as said, it's not that bad for me. It is Friday, let's first have a great weekend 😀

![grafik](https://user-images.githubusercontent.com/485313/91578360-54eea880-e94a-11ea-97ef-53a08acb2a9e.png)

**Comment by nikosdion** [comment] 2020-10-10 09:42
Closing as invalid. I have not been able to reproduce on 4 different development and 3 different live servers.

**Closed by nikosdion** 2020-10-10 09:42 UTC
Labels: invalid
