### ISSUE TITLE
Bug in backend after update to 3.10

### ISSUE THREAD

**Issue by rbuelund** [akeeba/loginguard#111] opened 2021-08-17 15:14 UTC
### Steps to reproduce the issue

Upgrade website to Joomla 3.10

### Expected result

Upgrade site to Joomla 3.10

### Actual result

Error and not possible to navigate backend: Viev class not found [class, file]: loginguardViewcaptive, /var/www/www.xxxxxx.dk/www/administrator/components/com_loginguard/views/captive/view.html.php 

File &lt;root&gt;/libraries/src/MVC/Factory/LegacyFactory.php Line 85

### Troubleshooting already performed

Please tell us about any troubleshooting you already performed and its results.

#### Mandatory information

Issues without this information can not and _will not_ be replied to.

* **Joomla! version**: 3.10
* **Am I using HTTPS**:  No
* **Server Operating System**:Linux
* **My device's Operating System**: Windows,
* **My device's Operating System version**: e.g. macOS Mojave
* **Browser**: Firefox,
* **Browser version**: x.y.z

#### Good to have information

You can skip some or all of this information. However, the more information you provide the faster and better we can help.

* **MySQL version**: x.y.z
* **Server type**: Apache, NginX, IIS, Lighttpd, LiteSpeed, ...
* **Server version**: x.y.z
* **Hosting company / Local server**: Enter the name of your site's hosting company or the prepackaged local server (e.g. MAMP, XAMPP, WAMPServer, ...) that you're using
* **Server Operating System version**: e.g. Windows 10, Ubuntu 16.04, ... Type N/A if it's a live host and you have no idea.

**Comment by nikosdion** [comment] 2021-08-17 15:17
Duplicate of https://github.com/akeeba/loginguard/issues/110

Fixed in version 5.0.2 released a few minutes ago.

**Closed by nikosdion** 2021-08-17 15:17 UTC
Labels: bug

**Comment by rbuelund** [comment] 2021-08-17 15:38
Perfect - thank you!
